In [1]:
import torch

In [2]:
tensor = torch.arange(12)

In [3]:
tensor.shape

torch.Size([12])

In [4]:
tensor.numel() # number of element

12

In [7]:
tensor = tensor.reshape(3,4)
tensor

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

# 广播机制
即使形状不同，我们仍然可以通过调用 广播机制 （broadcasting mechanism） 来执行按元素操作


In [10]:
# a,b都有两个维度
# 组合都变成 3x2 的tensor，再相加
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [11]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

# 原地操作
避免tensor自我复制占内存

In [13]:
Y = a+b
X = a+b
# id 类似c的指针，唯一标识
before = id(Y)
Y = Y + X
id(Y) == before

False

In [14]:
# 原地操作
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 2302676466800
id(Z): 2302676466800


如果在后续计算中没有重复使用 X，我们也可以使用 X[:] = X + Y 或 X += Y 来减少操作的内存开销

In [15]:
before = id(X)
X += Y
id(X) == before

True

# numpy 与 torch的转换
将大小为1的张量转换为 Python 标量

In [16]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)# 注意item()

(tensor([3.5000]), 3.5, 3.5, 3)