给定具有相同形状的任意两个张量，任何按元素二元运算的结果都将是相同形状的张量

In [47]:
import torch
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()# 另外开辟一块内存
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

表示任意形状张量的元素和(丢掉维度)

In [48]:
A.shape ,A.sum()#scalar
print(A)


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


In [49]:
A = A.reshape(2,5,2)
A_sum_axis0 = A.sum(axis=0)#最后长成剩下维度的shape
A,A_sum_axis0,A_sum_axis0.shape

(tensor([[[ 0.,  1.],
          [ 2.,  3.],
          [ 4.,  5.],
          [ 6.,  7.],
          [ 8.,  9.]],
 
         [[10., 11.],
          [12., 13.],
          [14., 15.],
          [16., 17.],
          [18., 19.]]]),
 tensor([[10., 12.],
         [14., 16.],
         [18., 20.],
         [22., 24.],
         [26., 28.]]),
 torch.Size([5, 2]))

In [50]:
A_sum_axis1 = A.sum(axis=1)#最后长成剩下维度的shape
A_sum_axis1,A_sum_axis1.shape

(tensor([[20., 25.],
         [70., 75.]]),
 torch.Size([2, 2]))

也可以按两个维度求和 

In [51]:
A_sum_axis0_1 = A.sum(axis=[0,1])#最后长成剩下维度的shape
A_sum_axis0_1,A_sum_axis0_1.shape

(tensor([ 90., 100.]), torch.Size([2]))

# 平均值（mean或average）

In [52]:
A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

In [53]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([[ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [11., 12.],
         [13., 14.]]),
 tensor([[ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [11., 12.],
         [13., 14.]]))

计算总和或均值时保持轴数不变

In [54]:
A = A.reshape(2,2,5)
A_sum_1 = A.sum(axis=1,keepdims=True)
A,A_sum_1,A_sum_1.shape

(tensor([[[ 0.,  1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.,  9.]],
 
         [[10., 11., 12., 13., 14.],
          [15., 16., 17., 18., 19.]]]),
 tensor([[[ 5.,  7.,  9., 11., 13.]],
 
         [[25., 27., 29., 31., 33.]]]),
 torch.Size([2, 1, 5]))

通过广播将A除以sum_A

In [55]:
A / A_sum_1#方便做广播，因为广播要求维度要相同

tensor([[[0.0000, 0.1429, 0.2222, 0.2727, 0.3077],
         [1.0000, 0.8571, 0.7778, 0.7273, 0.6923]],

        [[0.4000, 0.4074, 0.4138, 0.4194, 0.4242],
         [0.6000, 0.5926, 0.5862, 0.5806, 0.5758]]])

某个轴计算A元素的累积总和

In [56]:
A.cumsum(axis=0)

tensor([[[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.]],

        [[10., 12., 14., 16., 18.],
         [20., 22., 24., 26., 28.]]])

# 乘法
- 向量dot点乘
- mv(matrix and vector)
- mm(matrix and matrix)
- IL1 范数，它表示为向量元素的绝对值之和
- 范数 L2范数是向量元素平方和的平方根
- 矩阵 的弗罗贝尼乌斯范数（Frobenius norm）是矩阵元素平方和的平方根

In [57]:
#DOT,仅限vectors
x = torch.arange(4,dtype=torch.float32)
y= torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [66]:
# matrix and vector
x = torch.ones(2,dtype=torch.float32)
A = torch.arange(8,dtype=torch.float32).reshape(4,2)
x,A,torch.mv(A,x)

(tensor([1., 1.]),
 tensor([[0., 1.],
         [2., 3.],
         [4., 5.],
         [6., 7.]]),
 tensor([ 1.,  5.,  9., 13.]))

In [68]:
B = A
A,B,torch.mm(A,B.T)

(tensor([[0., 1.],
         [2., 3.],
         [4., 5.],
         [6., 7.]]),
 tensor([[0., 1.],
         [2., 3.],
         [4., 5.],
         [6., 7.]]),
 tensor([[ 1.,  3.,  5.,  7.],
         [ 3., 13., 23., 33.],
         [ 5., 23., 41., 59.],
         [ 7., 33., 59., 85.]]))

In [71]:
# L1范数
torch.abs(x).sum()

tensor(2.)

In [70]:
# L2 范数
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [72]:
# 矩阵元素平方和的平方根
torch.norm(torch.ones((4, 9)))

tensor(6.)