# 自定义层
构造一个没有任何参数的自定义层

In [2]:
import imp
import torch 
import torch.nn.functional as F
from torch import nn

class CenterLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self,X):
        return X-X.mean()

layer = CenterLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

C:\Users\Tamako\AppData\Local\Temp\ipykernel_3668\1967921088.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp


tensor([-2., -1.,  0.,  1.,  2.])

将层作为组件合并到构建更复杂的模型中

In [3]:
#CenterLayer作为组件
net = nn.Sequential(nn.Linear(8,128),CenterLayer())

Y = net(torch.rand(4,8))

Y.mean()

tensor(3.7253e-09, grad_fn=<MeanBackward0>)

带参数的层

In [5]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-1.3718,  0.1101,  0.2681],
        [-0.4742, -0.8941, -1.0896],
        [-0.4665,  0.6144, -0.3811],
        [-0.9435, -0.2861, -0.5069],
        [ 1.2783, -0.0481,  0.7606]], requires_grad=True)

使用自定义层直接执行正向传播计算

In [6]:
linear(torch.rand(2, 5))

tensor([[0.0000, 0.9389, 0.0000],
        [0.0000, 0.9788, 0.2786]])

使用自定义层构建模型

In [7]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.],
        [0.]])