# 读写文件
## 1 简单读写操作
### 1.1 加载和保存张量

In [3]:
import torch 
from torch import nn
from  torch.nn import functional as F 

x = torch.arange(4)
torch.save(x,'x-file')
x


tensor([0, 1, 2, 3])

In [4]:
x2 = torch.load('x-file')
x2

tensor([0, 1, 2, 3])

### 1.2 存储一个张量列表，然后把它们读回内存

In [5]:
y = torch.zeros(4)
torch.save([x,y],'x-files')


In [6]:
x2, y2 = torch.load('x-files')
(x2,y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

### 1.3 写入或读取从字符串映射到张量的字典

In [7]:
mydict = {'x':x,'y':y}
torch.save(mydict,'mydict')


In [8]:
mydict2 = torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

## 2 加载和保存模型参数

In [9]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20,256)
        self.output = nn.Linear(256,10)

    def forward(self,x):
        return self.output(F.relu(self.hidden(x)))

net = MLP()
X = torch.rand(size=(2,20))
Y = net(X)

将模型的参数存储为一个叫做“mlp.params”的文件

In [12]:
# net.state_dict()
torch.save(net.state_dict(),'mpl.params')

实例化了原始多层感知机模型的一个备份。 直接读取文件中存储的参数

In [15]:
#实例化一个模型，来接收参数
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [16]:
#检验加载的model参数
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])