# 汇聚层
实现汇聚层的正向传播

In [22]:
import torch 
from d2l import torch as d2l
from torch import nn

def pool2d(X,pool_size,mode='max'):
    p_h,p_w = pool_size
    Y = torch.zeros(X.shape[0] - p_h + 1 ,X.shape[1] - p_w + 1)
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i,j] = X[i:i+p_h,j:j+ p_w].max()
            elif mode == 'avg':
                Y[i,j] = X[i:i+p_h,j:j+ p_w].mean()

    return Y


验证二维最大汇聚层的输出

In [23]:
X = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])

X.shape #3x3
pool2d(X, (2, 2))

tensor([[4., 5.],
        [7., 8.]])

验证平均汇聚层

In [24]:
pool2d(X, (2, 2), 'avg')

tensor([[2., 3.],
        [5., 6.]])

填充和步幅

In [41]:
#批量大小？（一次性处理的矩阵个数） ， channel ，4x4的矩阵
X = torch.arange(24, dtype=torch.float32).reshape((2, 1, 3, 4))
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]]],


        [[[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]]])

深度学习框架中的步幅与池化窗口的大小相同

In [42]:
# stride = kernelsize = 3
pool2d = nn.MaxPool2d(2)
pool2d

MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)

In [43]:
pool2d(X)

tensor([[[[ 5.,  7.]]],


        [[[17., 19.]]]])

填充和步幅可以手动设定

In [44]:
# 上下左右都padding 1
pool2d = nn.MaxPool2d(3,padding=1,stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [ 9., 11.]]],


        [[[17., 19.],
          [21., 23.]]]])

设定一个任意大小的矩形池化窗口，并分别设定填充和步幅的高度和宽度

In [45]:
pool2d = nn.MaxPool2d((2, 3), padding=(1, 1), stride=(2, 3))
pool2d(X)

tensor([[[[ 1.,  3.],
          [ 9., 11.]]],


        [[[13., 15.],
          [21., 23.]]]])

汇聚层在每个输入通道上单独运算

In [47]:
X = torch.arange(16, dtype=torch.float32).reshape((1, 1, 4, 4))

X = torch.cat((X, X + 1), 1)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [48]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])